version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./static:/app/static
      - ./media/:/app/media

    env_file:
      - .prod.env

    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - DATABASE_URL=postgres://postgres:postgres@db:5432/order_management
  
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_management
    ports:
      - "5432:5432"

volumes:
  postgres_data: